import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Red_Hat_Display } from "next/font/google";

import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer";

const outfit = Outfit({ subsets: ["latin"] });

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-had-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://ethrome.org",
    siteName: "ETHRome",
    images: [
      {
        url: "https://nextjs.org/og.png", // Must be an absolute URL
        width: 800,
        height: 600,
      },
      {
        url: "https://nextjs.org/og-alt.png", // Must be an absolute URL
        width: 1800,
        height: 1600,
        alt: "My custom alt",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${redHatDisplay.variable} bg-ethrome-BlackerThanPurple`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
