import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Red_Hat_Display } from "next/font/google";

import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer";

const outfit = Outfit({ subsets: ["latin"] });

const redHatDisplay = Red_Hat_Display({ subsets: ["latin"], variable:"--font-red-had-display" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${redHatDisplay.variable} bg-ethrome-BlackerThanPurple`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
